---
title: "Hiring Analysis"
author: "Rachel"
date: "2021/4/20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#这个chunk用来read csv文件和写入package
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readxl)
library(readr)
library(janitor)
library(ggthemes)
library("gridExtra")
library(opendatatoronto)
library(lme4)


black_saber_current_employees <- read_csv("rstudio-export/black-saber-current-employees.csv")

phase1_hiring <- read_csv("rstudio-export/phase1-new-grad-applicants-2020.csv")

phase2_hiring <- read_csv("rstudio-export/phase2-new-grad-applicants-2020.csv")

phase3_hiring <- read_csv("rstudio-export/phase3-new-grad-applicants-2020.csv")

final_hiring <- read_csv("rstudio-export/final-hires-newgrad_2020.csv")


```

```{r}
#简单检索发现没有NA数据，先看看Phase 1多少个男性多少个女性
Gender_Dist_P1 <- phase1_hiring %>%
  ggplot(aes(x=gender, fill = gender)) +
  geom_bar() +
  scale_fill_manual(name = "Gender", values = c("#FDAF01", "#01B9FD", "#7501FD")) +
  labs(x = "Gender", y="Count", title = "Gender Distribution at Phase 1") +
  theme_minimal()
ggsave("Gender Distribution Phase 1 Hiring.png", Gender_Dist_P1, width = 6, height = 4)
```

```{r}
#Phase 1 GPA和Gender
GPA_Gender <- phase1_hiring %>%
  ggplot(aes(x = gender, y = gpa, color = gender)) +
  geom_boxplot() +
  scale_color_manual(name = "Gender", values = c("#FDAF01", "#01B9FD", "#7501FD")) +
  labs(title = "GPA vs. Gender at Phase 1 Hiring", x = "Gender", y = "GPA") +
  theme_minimal()
GPA_Gender
ggsave("GPA vs. Gender.png", GPA_Gender)
```
```{r}
# Phase 1 GPA 和 Results 和 gender
GPA_Gender_Results <- phase1_with_results %>%
  ggplot(aes(x = Results, y = gpa, color = gender)) +
  geom_boxplot() +
  scale_color_manual(name = "Gender", values = c("#FDAF01", "#01B9FD", "#7501FD")) +
  labs(title = "GPA vs. Gender with Phase 1 Results", x = "Results", y = "GPA") +
  theme_minimal()
ggsave("GPA vs. Gender with Phase 1 Results.png", GPA_Gender_Results)
```


```{r}
# Phase 2 男女比
phase2_hiring %>%
  ggplot(aes(x=gender, fill = gender)) +
  geom_bar() +
  scale_fill_manual(name = "Gender", values = c("#01AAFD", "#01FD5C", "#FD5D01")) +
  labs(x = "Gender", y="Count", title = "Gender Distribution at Phase 2") +
  theme_minimal()
```
```{r}
#创建dataframe 只保留id和gender因为phase 3和final里只有id
df_identify_MF <- phase1_hiring %>%
  select(c(applicant_id, gender))
phase3_hiring_with_gender <- df_identify_MF %>%
  right_join(phase3_hiring, by = "applicant_id")
```

```{r}
#Phase 3 男女比
Gender_Dist_Passed_Phase3 <- phase3_hiring_with_gender %>%
  ggplot(aes(x=gender, fill = gender)) +
  geom_bar() +
  scale_fill_manual(name = "Gender", values = c("#FDAF01", "#7501FD")) +
  labs(x = "Gender", y="Count", title = "Gender Comparison of Whom Passed Phase 3") +
  theme_minimal()
ggsave("Gender Distribution Passed Phase 3.png", Gender_Dist_Passed_Phase3, width = 6, height = 4)
```

```{r}
#Final phase标注男女
final_hiring_with_gender <- df_identify_MF %>%
  right_join(final_hiring, by = "applicant_id")
```

```{r}
#Final hiring男女比
Final_Hiring_Dist <- final_hiring_with_gender %>%
  ggplot(aes(x=gender, fill = gender)) +
  geom_bar() +
  scale_fill_manual(name = "Gender", values = c("#FDAF01", "#7501FD")) +
  labs(x = "Gender", y="Count", title = "Gender Comparison at Final Phase") +
  theme_minimal()
Final_Hiring_Dist
ggsave("yichen fig 2.png", Final_Hiring_Dist)
```

```{r}
# Phase 1 -> Phase 2, Phase 2 -> Phase 3, Phase 3 -> Final Results
# 每个阶段的results都给你标注了出来

phase2_results <- phase2_hiring %>%
  select("applicant_id") %>%
  mutate("Results" = "Pass")

phase1_with_results <- left_join(phase1_hiring, phase2_results, by = "applicant_id") %>%
  mutate("Results" = replace_na(Results, "Fail"))


phase2_with_results <- phase2_hiring %>%
  full_join(phase3_hiring, by = "applicant_id") %>%
  mutate(Pass = ifelse(applicant_id %in% phase3_hiring$applicant_id, 1, 0)) 

phase3_with_results <- phase2_hiring %>%
  right_join(phase3_hiring, by = "applicant_id") %>%
  mutate(Pass = ifelse(applicant_id %in% final_hiring$applicant_id, 1, 0))
```

```{r}
# Phase 1 -> Phase 2 Models和极大似然估计测试 model1有gender model2无gender, random effect is applicant_id
model_1 <- glm(as.factor(Results) ~ gender + cover_letter + cv + gpa + extracurriculars + work_experience , data = phase1_with_results, family = binomial)

model_2 <- glm(as.factor(Results) ~ cover_letter + cv + gpa + extracurriculars + work_experience , data = phase1_with_results, family = binomial)

lmtest::lrtest(model_1, model_2)

summary(model_2)
```

```{r}
# Phase 2 -> Phase 3
model_3 <- glm(Pass ~ technical_skills + writing_skills + speaking_skills + leadership_presence + gender, data = phase2_with_results, family = binomial)

model_4 <- glm(Pass ~ technical_skills + writing_skills + speaking_skills + leadership_presence, data = phase2_with_results, family = binomial)

lmtest::lrtest(model_3, model_4)

summary(model_4)
```

```{r}
# Phase 3 -> Final
model_5 <- glmer(Pass ~ interviewer_rating_1 + interviewer_rating_2 + gender + (1|applicant_id), data = phase3_with_results , family = binomial, nAGQ = 0)

model_6 <- glmer(Pass ~ interviewer_rating_1 + interviewer_rating_2 + (1|applicant_id), data = phase3_with_results , family = binomial, nAGQ = 0)

lmtest::lrtest(model_5, model_6)

summary(model_6)
```




